static_analyses:
  ignore_files:
    - karr_lab_build_utils/templates/*
    - karr_lab_build_utils/templates/**/*
  ignore_unused_requirements:
    - sphinx_fontawesome
    - sphinx_rtd_theme
    - sphinxcontrib_addmetahtml
    - sphinxcontrib_bibtex
    - sphinxcontrib_googleanalytics
    - sphinxcontrib_spelling
    - sphinxprettysearchresults
    - wheel
  ignore_missing_requirements: []
downstream_dependencies:
  - bcforms
  - bpforms
  - conv_opt
  - datanator
  - datanator_query_python
  # - datanator_rest_api
  - de_sim
  - gdoc_down
  - h1_hesc
  - intro_to_wc_modeling  
  - karr_lab_aws_manager
  - obj_tables_test_migration_repo
  - mycoplasma_pneumoniae
  - nose2unitth
  - obj_tables
  - pkg_utils
  - rand_wc_model_gen
  - unitth  
  - wc_analysis
  - wc_cli
  - wc_env_manager
  - wc_kb
  - wc_kb_gen
  - wc_lang
  - wc_model_gen
  - wc_onto
  - wc_rules
  - wc_sandbox
  - wc_sim
  - wc_test
  - wc_utils
email_notifications:
  - jonrkarr@gmail.com
