static_analyses:
  ignore_files:
      - karr_lab_build_utils/templates/*
downstream_dependencies:
  - conv_opt
  - datanator_website
  - gdoc_down
  - h1_hesc
  - intro_to_wc_modeling
  - kinetic_datanator
  - mycoplasma_pneumoniae
  - nose2unitth
  - obj_model
  - pkg_utils
  - random_wc_model_generator
  - unitth
  - wc_analysis
  - wc_kb
  - wc_lang
  - wc_rules
  - wc_sim
  - wc_utils
email_notifications:
  - jonrkarr@gmail.com
