version: 2
jobs:
  build:
    docker:
    - image: karrlab/wc_env_dependencies:latest
    working_directory: /root/project
    parallelism: 2
    steps:
      # Clone repository
      - checkout

      # Load packages from cache
      - restore_cache: &restore_req_cache
          keys:
            - v24-{{ arch }}-{{ .Branch }}-{{ checksum "/etc/docker-image-tag" }}-{{ checksum "requirements.txt" }}

      # Python 3 installation tasks
      - run: &install_pkg_utils
          name: Install pkg_utils (Python 3)
          command: python3 -m pip install -U git+https://github.com/KarrLab/pkg_utils.git#egg=pkg_utils
      - run: &install_karr_lab_build_utils
          name: Install karr_lab_build_utils (Python 3)
          command: |
            python3 -m pip install -U git+https://github.com/KarrLab/sphinxcontrib-googleanalytics.git#egg=sphinxcontrib_googleanalytics
            python3 -m pip install -U git+https://github.com/KarrLab/wc_utils.git#egg=wc_utils[all]
            python3 -m pip install -U -e .[all]
      - run: &install_config
          name: Install package configuration files including credentials
          command: karr_lab_build_utils3 download-install-package-config-files

      # Save packages to cache
      - save_cache: &save_req_cache
          key: v24-{{ arch }}-{{ .Branch }}-{{ checksum "/etc/docker-image-tag" }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.7/site-packages

      # Test code
      - run:
          name: Test code
          command: |
            set +e

            # Python 3
            python3 -m pip install -U -e .[all] \
            && karr_lab_build_utils3 run-tests \
              --n-workers ${CIRCLE_NODE_TOTAL} --i-worker ${CIRCLE_NODE_INDEX} \
              --with-xunit \
              --with-coverage
            TEST_EXIT_CODE_PY3=$?

            # Calculate exit code and save to file for reading by the next step
            if [[ $TEST_EXIT_CODE_PY3 -eq 0 ]]; then
              echo "0" > TEST_EXIT_CODE
              exit 0
            else
              echo "0" > TEST_EXIT_CODE
              exit 1
            fi

      # store results
      - store_test_results:
          path: /root/project/tests/reports
      - store_artifacts:
          path: /root/project/tests/reports
          destination: reports
      - store_artifacts:
          path: /root/project/logs
          destination: logs
      - persist_to_workspace:
          root: /root/project
          paths:
            - tests/reports

  report:
    docker:
    - image: karrlab/wc_env_dependencies:latest
    working_directory: /root/project
    parallelism: 1
    steps:
      # Clone repository
      - checkout

      # Load packages from cache
      - *restore_req_cache

      # Python 3 installation tasks
      - *install_pkg_utils
      - *install_karr_lab_build_utils
      - *install_reqs
      - *install_config

      # access reports saved by test job(s)
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy workspace
          when: always
          command: |
            cp -R /tmp/workspace/tests/reports /root/project/tests/reports

      # Generate reports, archive results, and send notifications
      - run:
          name: Generate reports, archive results, and send notifications
          when: always
          command: |
            if [[ -f TEST_EXIT_CODE ]]; then
              INSTALLATION_EXIT_CODE=0
              TEST_EXIT_CODE=$(<TEST_EXIT_CODE)
            else
              INSTALLATION_EXIT_CODE=1
              TEST_EXIT_CODE=1
            fi

            karr_lab_build_utils3 do-post-test-tasks $INSTALLATION_EXIT_CODE $TEST_EXIT_CODE

      # store results
      - store_artifacts:
          path: /root/project/docs/_build/html
          destination: docs

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: karr_lab
      - report:
          context: karr_lab
