name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pygit2
  - python
  - sphinx
  - pip:
    - configparser
    - sphinx_rtd_theme
    - robpol86-sphinxcontrib-googleanalytics
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling
    
